name: geospatial-images-dg-build

on: 
    workflow_dispatch:
    push:
        paths:
        - 'datagenerators/geospatial-images/datagenerator/**'
        - '.github/workflows/geospatial-images-generator-build.yaml'

jobs:
  build-datagenerator-geospatial-images-amd64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/data-generator-build.yaml@main
    with:
      REGISTRY: ghcr.io
      APP_NAME: datagenerator-geospatial-images
      ANNOTATION: azure-orbital-space-sdk-data-generators.yaml
      WORKFLOW_AGENT: ubuntu-latest
      ARCHITECTURE: amd64
      DOCKER_FILE: ./datagenerators/geospatial-images/datagenerator/Dockerfiles/Dockerfile
      REPO_DIR: ./datagenerators/geospatial-images/datagenerator
      YAML_STAGING_DIRECTORY: /var/spacedev/yamls
      YAML_FOLDER_PATH: ./datagenerators/geospatial-images/datagenerator/k3s
      YAML_FILE_NAME: datagenerator-geospatial-images.yaml
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

  build-datagenerator-geospatial-images-arm64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/data-generator-build.yaml@main
    with:
      REGISTRY: ghcr.io
      APP_NAME: datagenerator-geospatial-images
      ANNOTATION: azure-orbital-space-sdk-data-generators.yaml
      WORKFLOW_AGENT: spacesdk-ubuntu-2204LTS-arm64
      ARCHITECTURE: arm64
      DOCKER_FILE: ./datagenerators/geospatial-images/datagenerator/Dockerfiles/Dockerfile
      REPO_DIR: ./datagenerators/geospatial-images/datagenerator
      YAML_STAGING_DIRECTORY: /var/spacedev/yamls
      YAML_FOLDER_PATH: ./datagenerators/geospatial-images/datagenerator/k3s
      YAML_FILE_NAME: datagenerator-geospatial-images.yaml
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}